version: "3.8"

services:
  nginx-web:
    image: nginx:1.27.2
    volumes: 
      - SwarmVol:/etc/nginx/SwarmVol
    deploy:
      replicas: 3
    ports: 
      - "80:80"    # Expose on port 80

volumes: 
  SwarmVol: